#!/bin/bash
# https://discuss.elastic.co/t/elasticsearch-7-17-7-does-not-start-java-security-accesscontrolexception-access-denied/318013/6

# Set to max mem 256GB
echo "vm.max_map_count=2097152" >> /etc/sysctl.conf
sysctl -p /etc/sysctl.conf

# Network
docker network create ek --attachable

# Docker Volumes
docker volume create elasticsearch

# docker-compose setup

mkdir $PWD/ek

cat > $PWD/ek/docker-compose.yaml <<'EOF'
services:
  elasticsearch:
    image: elasticsearch:8.5.0
    container_name: elasticsearch
    restart: unless-stopped
    networks:
      - ek
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.monitoring.collection.enabled=false"
      - "xpack.security.enabled=true"
      - "ELASTIC_PASSWORD=cloudgeeks"
      - "ES_JAVA_HOME=/usr/lib/jvm/default-java"
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 30
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      
      
  kibana:
    image: kibana:8.5.0
    restart: unless-stopped
    networks:
      - ek
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
volumes:
  elasticsearch:
networks:
  ek:
   external: true
EOF


docker compose -f ./ek/docker-compose.yaml -p ek up -d


# ENDPOINT='http://localhost:9200'

# export ENDPOINT

# curl -X GET "${ENDPOINT}/_cluster/health?pretty"

# curl -X GET "${ENDPOINT}/_cat"

# curl -X GET "${ENDPOINT}/_cat/nodes?v"

# curl -X GET "${ENDPOINT}/_cat/indices?v"


# End
